### ISSUE TITLE
Make focal dependent on dol only

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/focal#2]
For this, need to replace the use of 
[py2store.LocalBinaryStore](https://github.com/i2mint/py2store/blob/5edf6a06d5108ed51235590f672a5a6e67262ffa/py2store/stores/local_store.py#L173)
with
[dol.Files](https://github.com/i2mint/dol/blob/5e784cebf535b5865e658a7a9e467d07fc8c6aee/dol/filesys.py#L317)

But, see that their inits are different.
`LocalBinaryStore` has the `__init__` of 
[FilepathFormatKeys](https://github.com/i2mint/py2store/blob/c563b6a3788425eba75f75d6763df92bcd4ed7b0/py2store/persisters/local_files.py#L325):

```python
        path_format: str, 
        max_levels: int = inf
```

 but `Files` the init of 
[FileSysCollection](https://github.com/i2mint/dol/blob/5e784cebf535b5865e658a7a9e467d07fc8c6aee/dol/filesys.py#L132):

```python
        rootdir,
        subpath='',
        pattern_for_field=None,
        max_levels=None,
        *,
        include_hidden=False,
        assert_rootdir_existence=False,
```

To keep the capability of `LocalBinaryStore`, one can make a `LocalBinaryStore` class (subclass of `Files`) whose init forwards to the `Files` init based on an init with `path_format` and `max_levels` only. 
To do this, know that `path_format` is more or less equal to `os.path.join(rootdir, subpath)`. 

Good occasion to write a few tests.

**Comment by cavart28** [comment]
My failed attempt at it:

`
from dol.filesys import Files

class LocalBinaryStore(Files):

    def __init__(self, path_format, max_levels=None):
        dirs = path_format.split(os.sep)

        first_bracket_idx = None
        for idx, dir in enumerate(dirs):
            if '{}' in dir:
                first_bracket_idx = idx
                break

        if first_bracket_idx is not None:
            rootdir = ''.join(dirs[:first_bracket_idx])
            subpath = ''.join(dirs[first_bracket_idx:])

        else:
            rootdir = path_format
            subpath = ''

        super().__init__(rootdir=rootdir, subpath=subpath, max_levels=max_levels)`

yielding:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/13766983/151374168-4cb06563-5748-4615-b952-f4445bfaf5bb.png">
